sudo: required
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
services:
  - docker
cache: pip
install:
  - pip install coveralls
  - python setup.py install
before_script:
  - docker pull tenforce/virtuoso
  - sudo docker run -d --name virtuoso -p 127.0.0.1:8890:8890 -p 127.0.0.1:1111:1111  -e DBA_PASSWORD=dba -e SPARQL_UPDATE=true -e DEFAULT_GRAPH=http://localhost:8890/DAV --net="host" -t tenforce/virtuoso
  - docker ps -a
  - sleep 45
script: python setup.py nosetests
after_success:
  coveralls
